version: '2'
services:
    cargomanagmentsystem-app:
        image: cargomanagmentsystem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cargomanagmentsystem-postgresql:5432/CargoManagmentSystem
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cargomanagmentsystem-postgresql:
        extends:
            file: postgresql.yml
            service: cargomanagmentsystem-postgresql
